version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - export BUCKET=production-sort-artifacts
      - aws cloudformation package --template-file lambda/template.yml --s3-bucket $BUCKET --output-template-file lambda/outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
  base-directory: lambda